import type { LocationDefinition } from '../types';

export const LOCATIONS: Record<string, LocationDefinition> = {
  dorset_street: {
    id: 'dorset_street',
    name: 'Dorset Street',
    shortName: 'Dorset Street',
    act: 1,
    atmosphere: 'Foggy mornings, muddy roads, constant noise from vendors and carts. A crowded and impoverished street in Whitechapel.',
    description: "The air is thick with the smell of coal smoke and the press of humanity. A crowd has gathered outside Miller's Court, their whispers a low hum against the city's noise.",
    exits: ['millers_court', 'bucks_row'],
    interactables: ['police_barricade', 'street_lamps', 'lodging_house_entrances', 'crowd'],
    keyClues: ["Crowd rumors about Miller's Court", "Abberline can brief Watson on the situation"],
    criticalPathLead: "Speak with Inspector Abberline or enter Miller's Court to begin the investigation.",
    locationExaminedFlag: 'examined_dorset_street',
  },
  millers_court: {
    id: 'millers_court',
    name: "13 Miller's Court",
    shortName: "13 Miller's Court",
    act: 1,
    atmosphere: 'Claustrophobic, quiet, and deeply unsettling. The room where Mary Jane Kelly was found.',
    description: 'A small rented room, barely large enough for the bed that dominates it. The fireplace is cold, but the air feels heavy with the weight of what occurred here.',
    exits: ['dorset_street'],
    interactables: ['the_bed', 'burned_clothing', 'examination_instruments', 'bloodstained_sheets'],
    keyClues: ['Killer had time and confidence', 'Burned clothing used for light', 'Extensive mutilation indicates medical familiarity'],
    criticalPathLead: "Examine the bed and fireplace, and speak with Dr. Bond to understand the brutality of the scene.",
    locationExaminedFlag: 'examined_millers_court',
  },
  bucks_row: {
    id: 'bucks_row',
    name: "Buck's Row",
    shortName: "Buck's Row",
    act: 2,
    atmosphere: 'Quiet and industrial. A narrow street lined with warehouses where Mary Ann Nichols was found.',
    description: 'The cobblestones are slick with damp. The warehouses loom like silent sentinels over the spot where the first victim was discovered.',
    exits: ['dorset_street', 'hanbury_street'],
    interactables: ['cobblestone_roadway', 'warehouse_doors', 'street_lamps'],
    keyClues: ['Killer approached Nichols calmly', 'Witnesses believed she was merely drunk'],
    criticalPathLead: "Review the witness testimony and examine the street to understand the killer's non-threatening approach.",
    locationExaminedFlag: 'examined_bucks_row',
  },
  hanbury_street: {
    id: 'hanbury_street',
    name: 'Hanbury Street',
    shortName: 'Hanbury Street',
    act: 2,
    atmosphere: 'Crowded working-class neighborhood. The backyard behind 29 Hanbury Street where Annie Chapman was found.',
    description: 'The yard is small, enclosed by a wooden fence. It feels far too public for such a private horror.',
    exits: ['bucks_row', 'dutfields_yard'],
    interactables: ['wooden_fence', 'yard_steps', 'ground_where_body_was_discovered'],
    keyClues: ['Organ removal (uterus)', 'Killer has anatomical familiarity'],
    criticalPathLead: "Examine the yard and speak with Dr. Bond about the anatomical precision of the organ removal.",
    locationExaminedFlag: 'examined_hanbury_street',
  },
  dutfields_yard: {
    id: 'dutfields_yard',
    name: "Dutfield's Yard",
    shortName: "Dutfield's Yard",
    act: 3,
    atmosphere: 'Lively due to the nearby club, but quiet within the yard itself. Where Elizabeth Stride was found.',
    description: 'A small yard beside the International Working Men\'s Club. The sounds of political discussion drift from the open windows above.',
    exits: ['hanbury_street', 'working_mens_club', 'mitre_square'],
    interactables: ['yard_entrance_gate', 'cart_path', 'club_doorway'],
    keyClues: ['Killer was interrupted', 'Only a throat wound — no mutilation'],
    criticalPathLead: "Inspect the entryway and speak with Louis Diemschutz to reconstruct the timeline of the interruption.",
    locationExaminedFlag: 'examined_dutfields_yard',
  },
  working_mens_club: {
    id: 'working_mens_club',
    name: "International Working Men's Club",
    shortName: "Working Men's Club",
    act: 3,
    atmosphere: 'Political discussions, cigarette smoke, crowded benches. A meeting hall for socialist workers.',
    description: 'The room is filled with the scent of cheap tobacco and the energy of debate. Posters and newspapers line the walls.',
    exits: ['dutfields_yard'],
    interactables: ['tables', 'posters', 'newspapers', 'club_members'],
    keyClues: ["Witness accounts of Stride's discovery", 'Social context of the neighbourhood'],
    criticalPathLead: "Interview the club members to gather witness accounts and understand the social tension.",
    locationExaminedFlag: 'examined_working_mens_club',
  },
  mitre_square: {
    id: 'mitre_square',
    name: 'Mitre Square',
    shortName: 'Mitre Square',
    act: 3,
    atmosphere: 'Cold and isolated with echoing footsteps. Where Catherine Eddowes was murdered.',
    description: 'A stone square within the City of London. The dark alleyways seem to swallow the light from the police lanterns.',
    exits: ['dutfields_yard', 'goulston_street'],
    interactables: ['alleyways', 'square_walls', 'police_lanterns'],
    keyClues: ['Kidney removal', 'Killer knew the city and its escape routes'],
    criticalPathLead: "Discuss the kidney removal with Dr. Bond and study the escape routes to build the killer's profile.",
    locationExaminedFlag: 'examined_mitre_square',
  },
  goulston_street: {
    id: 'goulston_street',
    name: 'Goulston Street',
    shortName: 'Goulston Street',
    act: 4,
    atmosphere: 'Busy street with tension due to recent unrest. Where a piece of Eddowes\' apron was found.',
    description: "The street is bustling, but the wall where the graffiti was discovered remains a point of grim fascination. The Metropolitan Police erased the chalk writing before it could be photographed.",
    exits: ['mitre_square', 'lusk_office'],
    interactables: ['graffiti_wall', 'apron_fragment_location'],
    keyClues: ['Killer moving between jurisdictions', 'Apron fragment links Mitre Square to Goulston Street', 'Graffito erased — possibly anti-Semitic'],
    criticalPathLead: "Examine the graffiti location and discuss the police decision to erase the crucial message.",
    locationExaminedFlag: 'examined_goulston_street',
  },
  lusk_office: {
    id: 'lusk_office',
    name: "George Lusk's Office",
    shortName: 'Lusk Office',
    act: 4,
    atmosphere: 'Cluttered with papers and letters. Meeting room of the Whitechapel Vigilance Committee.',
    description: 'The office is small and cramped, filled with the correspondence of a terrified district.',
    exits: ['goulston_street', 'bond_office'],
    interactables: ['parcel_box', 'from_hell_letter', 'kidney_parcel'],
    keyClues: ['From Hell letter with irregular spelling', 'Half a human kidney — Watson can confirm it is human'],
    criticalPathLead: "Examine the From Hell letter carefully — note the spelling — and have Watson examine the kidney parcel.",
    locationExaminedFlag: 'examined_lusk_office',
  },
  bond_office: {
    id: 'bond_office',
    name: "Dr. Bond's Office",
    shortName: 'Bond Office',
    act: 5,
    atmosphere: 'Clinical and quiet. Contains forensic records and anatomical specimens.',
    description: 'The room smells of formaldehyde and old paper. Medical reports are stacked neatly on the desk.',
    exits: ['lusk_office', 'private_asylum', 'baker_street'],
    interactables: ['medical_reports', 'anatomical_texts', 'specimen_jars', 'edmund_forensic_note'],
    keyClues: ["Edmund's forensic note contains 'prasarved' — matching the From Hell letter", 'Patterns across all five murders'],
    criticalPathLead: "Review the forensic reports carefully. Look for Edmund's handwritten notes — the spelling anomaly is the critical link.",
    locationExaminedFlag: 'examined_bond_office',
  },
  private_asylum: {
    id: 'private_asylum',
    name: 'The Private Asylum',
    shortName: 'Private Asylum',
    act: 6,
    atmosphere: 'Quiet, sterile, and unsettlingly calm. An institution outside London.',
    description: "The grounds are well-kept, but the high walls and locked doors speak of a different kind of poverty — the poverty of the mind.",
    exits: ['bond_office', 'baker_street'],
    interactables: ['patient_records', 'edmund_room_furnishings', 'superintendent'],
    keyClues: ["Edmund committed after Kelly's murder", 'Family discovered disturbing medical evidence — a preserved kidney'],
    criticalPathLead: "Speak with the superintendent and confront Edmund in his room. He will remain calm.",
    locationExaminedFlag: 'visited_private_asylum',
  },
  baker_street: {
    id: 'baker_street',
    name: '221B Baker Street',
    shortName: 'Baker Street',
    act: 6,
    atmosphere: 'Warm but reflective. Holmes and Watson\'s residence.',
    description: "The familiar clutter of our rooms at Baker Street is a welcome sight, though the case still hangs heavy in the air.",
    exits: ['dorset_street', 'bond_office', 'private_asylum'],
    interactables: ['watson_diary', 'holmes_violin', 'newspapers'],
    keyClues: ['Final deduction — all clues point to Edmund Halward', 'Historical ambiguity — no legal proof'],
    criticalPathLead: "Review your diary entries and discuss the final conclusions with Holmes. The truth lies in the sum of all clues.",
    locationExaminedFlag: 'examined_baker_street',
  },
};

export const OBJECT_DISPLAY_NAMES: Record<string, string> = {
  police_barricade: 'Police Barricade',
  street_lamps: 'Street Lamps',
  lodging_house_entrances: 'Lodging House Entrances',
  crowd: 'The Crowd',
  the_bed: 'The Bed',
  burned_clothing: 'Burned Clothing',
  examination_instruments: 'Examination Instruments',
  bloodstained_sheets: 'Bloodstained Sheets',
  cobblestone_roadway: 'Cobblestone Roadway',
  warehouse_doors: 'Warehouse Doors',
  wooden_fence: 'Wooden Fence',
  yard_steps: 'Yard Steps',
  ground_where_body_was_discovered: 'Ground (Body Discovery Site)',
  yard_entrance_gate: 'Yard Entrance Gate',
  cart_path: 'Cart Path',
  club_doorway: 'Club Doorway',
  tables: 'Tables',
  posters: 'Posters',
  newspapers: 'Newspapers',
  alleyways: 'Dark Alleyways',
  square_walls: 'Square Walls',
  police_lanterns: 'Police Lanterns',
  graffiti_wall: 'Graffiti Wall',
  apron_fragment_location: 'Apron Fragment Location',
  parcel_box: 'Parcel Box',
  from_hell_letter: 'The From Hell Letter',
  kidney_parcel: 'The Kidney Parcel',
  medical_reports: 'Forensic Examination Reports',
  anatomical_texts: 'Anatomical Textbooks',
  specimen_jars: 'Specimen Jars',
  edmund_forensic_note: "Edmund's Forensic Note",
  patient_records: 'Patient Records',
  edmund_room_furnishings: "Edmund's Room",
  superintendent: 'Asylum Superintendent',
  watson_diary: "Watson's Diary",
  holmes_violin: "Holmes' Violin",
  club_members: 'Club Members',
  city_police: 'City Police Officers',
};
