import type { NPCDefinition } from '../types';

export const NPCS: Record<string, NPCDefinition> = {
  holmes: {
    id: 'holmes',
    displayName: 'Sherlock Holmes',
    role: 'Consulting Detective',
    description: 'Holmes investigates the Whitechapel murders unofficially, approaching the Ripper case as an intellectual problem. He follows Watson everywhere.',
    speakingStyle: 'Precise and controlled. Short observations and carefully constructed deductions.',
    personality: ['Analytical', 'Calm under pressure', 'Intensely curious', 'Occasionally aloof'],
    publicKnowledge: [
      'Visited all five crime scenes and conducted independent forensic analysis',
      'The killer appeared non-threatening to victims — respectable-looking or known to them',
      'Anatomical removals required knowledge of organ location, not surgical mastery — the knowledge of a student',
      'Not panicked by Stride\'s interruption — completed a second murder same night within 45 minutes',
      'The "prasarved" spelling in the From Hell letter is a specific cognitive habit, matching other documents',
      'The killer has legitimate professional access to crime scenes and forensic records',
      'Murders stopped after Kelly — suggests capture, death, confinement, or removal from London',
    ],
    followingRule: 'follows_watson',
    followsNpcId: 'watson',
    canonicalLocationByAct: {
      1: 'dorset_street',
      2: 'bucks_row',
      3: 'dutfields_yard',
      4: 'goulston_street',
      5: 'bond_office',
      6: 'private_asylum',
    },
  },
  abberline: {
    id: 'abberline',
    displayName: 'Inspector Abberline',
    role: 'Scotland Yard Detective Inspector',
    description: 'Lead investigator for Scotland Yard. Experienced, honest, and deeply fatigued by the lack of progress.',
    speakingStyle: 'Direct and conversational. Practical rather than theoretical.',
    personality: ['Practical', 'Honest', 'Determined', 'Fatigued'],
    publicKnowledge: [
      'Leads the Metropolitan Police investigation from Commercial Street station',
      'Five victims: Mary Ann Nichols (31 Aug), Annie Chapman (8 Sep), Elizabeth Stride and Catherine Eddowes (30 Sep, double event), Mary Jane Kelly (9 Nov)',
      'The double event on 30 September was the worst night — two murders in 45 minutes, two different police jurisdictions',
      'City Police handled Eddowes at Mitre Square — inter-force coordination has been problematic throughout',
      'Commissioner Warren ordered the Goulston Street graffiti wiped before it could be photographed, to prevent anti-Jewish riots',
      'Over 2,000 people interviewed; no conclusive forensic link established to any individual',
      'The press — Star and Times in particular — prints speculation as fact and terrifies witnesses into silence',
      'No reliable witness has seen the killer with any victim; every description is contradictory',
      'George Lusk and the Vigilance Committee provide ground coverage but also pressure from below',
    ],
    followingRule: 'location_based',
    canonicalLocationByAct: {
      1: 'dorset_street',
      2: 'bucks_row',
      3: 'dutfields_yard',
      4: 'goulston_street',
      5: 'bond_office',
      6: 'private_asylum',
    },
  },
  bond: {
    id: 'bond',
    displayName: 'Dr. Thomas Bond',
    role: 'Police Surgeon',
    description: 'Responsible for examining the victims. Clinical, professional, and rarely speculates beyond medical facts.',
    speakingStyle: 'Technical and precise. Medical terminology.',
    personality: ['Clinical', 'Professional', 'Reserved'],
    publicKnowledge: [
      'Annie Chapman: uterus removed cleanly, incision shows familiarity with abdominal anatomy but not surgical mastery',
      'Catherine Eddowes: left kidney and uterus removed within minutes, efficiency consistent with prior practice',
      'Mary Jane Kelly: most extensive injuries, killer had several uninterrupted hours, fire burned for light',
      'Wrote a formal psychological profile in November 1888 for Assistant Commissioner Anderson',
      'His assessment: killer works alone, operates at night, has anatomical knowledge but no professional medical qualification',
      'Edmund Halward transcribed and catalogued all post-mortem reports',
      'Committed to reporting only what evidence substantiates — will not speculate beyond the record',
    ],
    followingRule: 'location_based',
    canonicalLocationByAct: {
      1: 'millers_court',
      2: 'bucks_row',
      3: 'dutfields_yard',
      4: 'lusk_office',
      5: 'bond_office',
      6: 'bond_office',
    },
  },
  edmund: {
    id: 'edmund',
    displayName: 'Edmund Halward',
    role: "Dr. Bond's Medical Assistant",
    description: 'Young, quiet, and outwardly respectable. Son of a physician. Studied medicine but left unexpectedly. Almost invisible. Never speaks unless directly addressed.',
    speakingStyle: 'Soft and measured. Avoids emotional language. Mundane and functional.',
    personality: ['Quiet', 'Polite', 'Reserved', 'Observant'],
    publicKnowledge: [
      'Medical assistant to Dr. Bond; present during post-mortem examinations',
      'Studied medicine but left formal training unexpectedly',
      'Quiet, polite, reserved — well-regarded by those who work with him',
    ],
    followingRule: 'follows_bond',
    followsNpcId: 'bond',
    canonicalLocationByAct: {
      1: 'millers_court',
      2: 'bucks_row',
      3: 'dutfields_yard',
      4: 'lusk_office',
      5: 'bond_office',
      6: 'private_asylum',
    },
  },
  lusk: {
    id: 'lusk',
    displayName: 'George Lusk',
    role: 'Chairman, Whitechapel Vigilance Committee',
    description: 'Recipient of the From Hell letter and the kidney parcel. Cautious and skeptical of hoaxes.',
    speakingStyle: 'Concerned but practical.',
    personality: ['Cautious', 'Uneasy about publicity', 'Skeptical'],
    publicKnowledge: [
      'Received the kidney parcel on 16 October 1888 — half a human kidney preserved in spirits of wine',
      'Initially assumed it was a prank by medical students; had it examined only after delay',
      'Dr. Openshaw confirmed the kidney was human tissue, female, approximately 45 years old, consistent with Bright\'s disease (matching Eddowes)',
      'The letter\'s phrasing stays with him: "I send you half the Kidne I took from one women prasarved it for you tother piece I fried and ate it was very nise"',
      'Founded the Whitechapel Vigilance Committee out of anger that the police were failing the neighbourhood',
      'Conducts nightly patrols; lobbied the Home Secretary for a government reward (refused)',
      'Distrusts the official investigation — not the men, but the machinery and inter-force politics',
    ],
    followingRule: 'fixed',
    canonicalLocationByAct: {
      1: 'lusk_office',
      2: 'lusk_office',
      3: 'lusk_office',
      4: 'lusk_office',
      5: 'lusk_office',
      6: 'lusk_office',
    },
  },
  diemschutz: {
    id: 'diemschutz',
    displayName: 'Louis Diemschutz',
    role: 'Steward, International Working Men\'s Club',
    description: 'Discovered Elizabeth Stride\'s body. Distressed witness.',
    speakingStyle: 'Shaken and direct.',
    personality: ['Distressed', 'Cooperative'],
    publicKnowledge: [
      'Found Elizabeth Stride\'s body in Dutfield\'s Yard on the night of 30 September',
      'His cart may have interrupted the killer mid-act — no mutilation followed the throat wound',
      'Witnessed or heard sounds that night; testimony was crucial to reconstructing the killer\'s timeline',
    ],
    followingRule: 'fixed',
    canonicalLocationByAct: {
      1: 'working_mens_club',
      2: 'working_mens_club',
      3: 'dutfields_yard',
      4: 'working_mens_club',
      5: 'working_mens_club',
      6: 'working_mens_club',
    },
  },
  superintendent: {
    id: 'superintendent',
    displayName: 'Asylum Superintendent',
    role: 'Superintendent of the Private Asylum',
    description: 'Professional but cautious about discussing patients.',
    speakingStyle: 'Measured and diplomatic.',
    personality: ['Professional', 'Guarded'],
    publicKnowledge: [
      'Manages a private asylum for those whose families wish discretion',
      'Edmund Halward has been a patient here following a family arrangement',
      'Speaks minimally about patients; will not volunteer information beyond what professional courtesy requires',
      'Believes private confinement is a humane solution for certain situations',
    ],
    followingRule: 'fixed',
    canonicalLocationByAct: {
      1: 'private_asylum',
      2: 'private_asylum',
      3: 'private_asylum',
      4: 'private_asylum',
      5: 'private_asylum',
      6: 'private_asylum',
    },
  },
};

export const NPC_DISPLAY_NAMES: Record<string, string> = {
  holmes: 'Sherlock Holmes',
  abberline: 'Inspector Abberline',
  bond: 'Dr. Thomas Bond',
  edmund: 'Edmund Halward',
  lusk: 'George Lusk',
  diemschutz: 'Louis Diemschutz',
  superintendent: 'Asylum Superintendent',
};
